### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Sixsoul** [NicoNekoDev/AstralLeaderboards#1]
### Information
Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)):
AstralLeaderboards settings (upload `plugins/AstralLeaderboards/settings.yml` to [Gist](https://gist.github.com/)): 

### Details
Describe your issue here.

**Comment by NicoNekoDev** [comment]
I'm no longer working on Minecraft plugins. Also this plugin was a prototype and I won't fix things to it as it won't correctly work in the first place.
